#!/usr/bin/env bash
set -euo pipefail
if [[ $# -lt 1 || -z "${CLAUDE_MODEL:-}" ]]; then
  echo 'usage: ANTHROPIC_API_KEY=... ANTHROPIC_BASE_URL=... CLAUDE_MODEL=<exact-model-id> bash scripts/narness-run-claude-pilots.sh /path/to/nession [output-dir]' >&2
  exit 64
fi
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXP="$ROOT/docs/topics/agent-native-repository-architecture/research/experiments/nession-terminal-session-reconnect-2026-09"
SOURCE_REPO="$(cd "$1" && pwd)"
OUTPUT_DIR="${2:-$ROOT/research-runs/claude-pilots}"
# The direct Claude Code path deliberately receives only the Anthropic credential
# and base URL. Never accidentally reuse a Codex credential.
if [[ -z "${ANTHROPIC_API_KEY:-}${ANTHROPIC_AUTH_TOKEN:-}" ]]; then
  echo 'Set ANTHROPIC_API_KEY (or ANTHROPIC_AUTH_TOKEN) before running pilots.' >&2
  exit 1
fi
if [[ -z "${ANTHROPIC_BASE_URL:-}" ]]; then
  echo 'Set ANTHROPIC_BASE_URL before running pilots.' >&2
  exit 1
fi
if [[ -n "${OPENAI_API_KEY:-}${CODEX_ACCESS_TOKEN:-}" ]]; then
  echo 'Unset OPENAI_API_KEY and CODEX_ACCESS_TOKEN before running Claude pilots.' >&2
  exit 1
fi
python3 "$ROOT/scripts/preflight-ai-native-codex-pilots.py" --skip-codex \
  --source-repo "$SOURCE_REPO" --output-dir "$OUTPUT_DIR"
python3 "$ROOT/scripts/narness-claude-adapter.py" --model "$CLAUDE_MODEL" --inspect-runtime
# Use shell quoting generated by Python rather than interpolating a model ID.
AGENT_CMD="$(python3 - "$ROOT" "$CLAUDE_MODEL" <<'PY'
import shlex,sys
print(shlex.join([sys.executable, sys.argv[1]+'/scripts/narness-claude-adapter.py', '--model',sys.argv[2], '--effort','high','--max-turns','100']))
PY
)"
for pair in T05:A T08:B T20:C; do
  task="${pair%:*}"; treatment="${pair#*:}"
  set +e
  python3 "$ROOT/scripts/ai-native-repo-experiment.py" \
    --source-repo "$SOURCE_REPO" --task "$EXP/runner/manifests/$task.json" \
    --treatments "$EXP/runner/treatments.json" --treatment "$treatment" --attempt 1 \
    --setup-cmd 'cd web && npm ci' --agent-cmd "$AGENT_CMD" --output-dir "$OUTPUT_DIR"
  rc=$?
  set -e
  if [[ "$rc" != 0 && "$rc" != 2 ]]; then exit "$rc"; fi
  python3 "$ROOT/scripts/score-ai-native-run.py" --run-dir "$OUTPUT_DIR/$task-$treatment-01" \
    --gold "$EXP/runner/gold.json" --treatment "$treatment" --update-run-json
  python3 "$ROOT/scripts/validate-ai-native-pilot.py" --run-dir "$OUTPUT_DIR/$task-$treatment-01"
done
python3 "$ROOT/scripts/freeze-ai-native-execution-profile.py" \
  --pilot "$OUTPUT_DIR/T05-A-01" --pilot "$OUTPUT_DIR/T08-B-01" --pilot "$OUTPUT_DIR/T20-C-01" \
  --profile-id claude-code-r6-r1 --output "$EXP/runner/execution-profile-r1.json"
python3 "$ROOT/scripts/generate-ai-native-formal-schedule.py" --replications 3 \
  --profile-id claude-code-r6-r1 --output "$EXP/runner/formal-schedule-r1.json"
python3 "$ROOT/scripts/freeze-ai-native-formal-plan.py" \
  --execution-profile "$EXP/runner/execution-profile-r1.json" \
  --schedule "$EXP/runner/formal-schedule-r1.json" --benchmark-lock "$EXP/BENCHMARK-LOCK.json" \
  --analysis-lock "$EXP/ANALYSIS-LOCK.json" --output "$EXP/runner/formal-plan-r1.lock.json"
echo 'Review and promote the real pilot handoff before formal collection.'
